### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by AlexCMueller** [benjaminrsherman/no-nn-simulator#1]
Maybe instead of downright blocking the page, you should have the popup say something like "or add this website to your subscription plan at only $1 per month"

**Comment by benjaminrsherman** [comment]
The problem with this idea is that I don't want to actually make a billing system... maybe the popup should just mention that the user *would* have to pay?

**Comment by AlexCMueller** [comment]
That's pretty much what I meant

**Comment by benjaminrsherman** [comment]
The overlay's been updated.
